name: e_commerce_flutter
description: E-Commerce App built in flutter using GetX


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # http: ^0.13.3

  get: ^4.6.5
  bottom_navy_bar: ^6.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.4.0
  animations: ^2.0.7
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  dio: ^5.2.0+1
  flutter_secure_storage: ^8.0.0
  infinite_scroll_pagination: ^3.2.0
  http_parser: ^4.0.2
  image_picker: ^0.8.8
  money_formatter: ^0.0.4

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2


flutter:

  uses-material-design: true

  assets:
    - assets/images/
